import companyLogo from "../../assests/logo/company_logo.jpg";
export const jobAllData = [
  {
    title: "frontend developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "node js developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "Team Lead",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "Project Manager",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "frontend developer",
    location: "Gurugram",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "frontend developer",
    location: "Gurugram",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "frontend developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "frontend developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "RPA developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "data scientic developer",
    location: "Gurugram",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: ".net developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "html developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "pythan developer",
    location: "Noida",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "java developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
  {
    title: "backend developer",
    location: "Delhi",
    companyName: "Uplers",
    description: "this job is for you  guys",
    companyLogo: companyLogo,
  },
];


export const AllLocation = ["Noida","Delhi","Gurugram"]